### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by rmarcelino4** [SoccerNet/sn-tracking#4]
I'm trying to use GoogleColab to run demo_track.py but this error appears. I couldn't figure out how to solve it... any tips?

2022-03-29 10:36:56.219 | INFO     | __main__:main:316 - Args: Namespace(aspect_ratio_thresh=1.6, camid=0, ckpt='pretrained/bytetrack_x_mot20.tar', conf=None, demo='video', device=device(type='cuda'), exp_file='exps/example/mot/yolox_x_mix_det.py', experiment_name='yolox_x_mix_det', fp16=True, fps=30, fuse=True, match_thresh=0.8, min_box_area=10, mot20=False, name=None, nms=None, path='./videos/quest.mp4', save_result=False, track_buffer=30, track_thresh=0.5, trt=False, tsize=None)
/usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
2022-03-29 10:37:00.035 | INFO     | __main__:main:326 - Model Summary: Params: 99.00M, Gflops: 791.73
2022-03-29 10:37:00.037 | INFO     | __main__:main:334 - loading checkpoint
Traceback (most recent call last):
  File "tools/demo_track.py", line 372, in <module>
    main(exp, args)
  File "tools/demo_track.py", line 335, in main
    ckpt = torch.load(ckpt_file, map_location="cpu")
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
**RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory**

**Comment by rmarcelino4** [comment]
I missed mentioning that I'm testing ByteTrack benchmark files...

**Comment by SilvioGiancola** [comment]
Hi @rmarcelino4 , it looks like the issue come from the zipped file, are you sure the zipped file is not corrupted?
Maybe @kl2005ad @Edwardf0t1 or @paulxinzhou can help on this issue?

**Comment by paulxinzhou** [comment]
Hi @rmarcelino4, it looks like the error is on the line  ckpt = torch.load(ckpt_file, map_location="cpu") of loading checkpoint. So my best guess would be your checkpoint file's path (containing pretrained weights) was not correct?
